Cookie updated targeting develop by NetworkToCode Cookie Drift Manager Tool
Template:

```
{
    "template": "https://github.com/networktocode-llc/cookiecutter-ntc.git",
    "dir": "python",
    "ref": "main",
    "path": "/__w/cookiecutter-nautobot-app-drift-manager/cookiecutter-nautobot-app-drift-manager/cookiecutter-ntc/python"
}
```

Cookie:

```
{
    "remote": "https://github.com/networktocode/netutils.git",
    "path": "/tmp/tmpiz94bhko/netutils",
    "repository_path": "/tmp/tmpiz94bhko/netutils",
    "dir": "",
    "branch_prefix": "drift-manager/develop",
    "context": {
        "codeowner_github_usernames": "@itdependsnetworks @jeffkala @qduk",
        "full_name": "Network to Code, LLC",
        "email": "info@networktocode.com",
        "github_org": "networktocode",
        "description": "Common helper functions useful in network automation.",
        "project_name": "netutils",
        "project_slug": "netutils",
        "repo_url": "https://github.com/networktocode/netutils",
        "base_url": "netutils",
        "project_python_name": "netutils",
        "project_python_base_version": "3.10",
        "project_with_config_settings": "no",
        "generate_docs": "yes",
        "version": "1.15.1",
        "original_publish_year": "2021",
        "_template": "/__w/cookiecutter-nautobot-app-drift-manager/cookiecutter-nautobot-app-drift-manager/cookiecutter-ntc/python",
        "_output_dir": "/tmp/tmpiz94bhko",
        "_repo_dir": "/__w/cookiecutter-nautobot-app-drift-manager/cookiecutter-nautobot-app-drift-manager/cookiecutter-ntc/python",
        "_checkout": null
    },
    "drift_managed_branch": "develop",
    "remote_name": "origin",
    "pull_request_strategy": "PullRequestStrategy.UPDATE_OR_CREATE",
    "post_actions": [],
    "baked_commit_ref": "b23a9ed5a4714810d83670ad47cc182764c6d464",
    "draft": false
}
```

CLI Arguments:

```
{
    "cookie_dir": "",
    "input": false,
    "json_filename": "",
    "output_dir": "",
    "push": true,
    "template": "./cookiecutter-ntc",
    "template_dir": "python",
    "template_ref": "main",
    "pull_request": "update-or-create",
    "post_action": [],
    "disable_post_actions": true,
    "draft": null,
    "drift_managed_branch": "develop"
}
```

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,10 +12,10 @@ jobs:
     steps:
       - uses: "actions/checkout@v4"
       - name: "Setup environment"
-        uses: "networktocode/gh-action-setup-poetry-environment@v6"
+        uses: "networktocode/gh-action-setup-poetry-environment@v7"
         with:
           poetry-version: "2.1.3"
-          python-version: "3.13"
+          python-version: "3.12"
           poetry-install-options: "--no-root"
       - name: "Run Poetry Build"
         run: "poetry build"
@@ -104,3 +104,62 @@ jobs:
                 }
               ]
             }
+
+  create-pr-to-develop:
+    if: "github.event.release.target_commitish == 'main'"
+    permissions:
+      contents: "write"
+      pull-requests: "write"
+    name: "Create a PR from main into develop"
+    needs:
+      - "publish-github"
+      - "publish-pypi"
+    runs-on: "ubuntu-latest"
+    steps:
+      - name: "Checkout main"
+        uses: "actions/checkout@v4"
+        with:
+          ref: "main"
+          fetch-depth: 0
+
+      - name: "Setup environment"
+        uses: "networktocode/gh-action-setup-poetry-environment@v6"
+        with:
+          poetry-version: "2.1.3"
+          poetry-install-options: "--no-root"
+
+      - name: "Create release branch from main"
+        id: "branch"
+        run: |
+
+          git config user.name "${{ github.actor }}"
+          git config user.email "${{ github.actor }}@users.noreply.github.com"
+
+          TAG_NAME="${{ github.event.release.tag_name }}"
+          VERSION="${TAG_NAME#v}"
+
+          BRANCH_NAME="release-${VERSION}-to-develop"
+
+          # Ensure release branch doesn't already exist
+          if git rev-parse --verify origin/$BRANCH_NAME > /dev/null 2>&1; then
+            echo "Error: Release branch $BRANCH_NAME already exists."
+            exit 1
+          fi
+
+          git checkout -b "$BRANCH_NAME"
+
+          poetry version prepatch
+          git add pyproject.toml && git commit -m "Bump version"
+          git push origin "$BRANCH_NAME"
+
+          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+
+      - name: "Create Pull Request to develop"
+        env:
+          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+        run: |
+          gh pr create \
+            --title "Post release ${{ github.event.release.tag_name }} to develop" \
+            --body "Please do a merge commit." \
+            --base "develop" \
+            --head "${{ steps.branch.outputs.branch_name }}"
